apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjogewogICAgICAgICAgICAiYXV0aCI6ICJkbUZ1YzJoQWJXOXpiR1Z5TG1sdU9tUnZjRjkyTVY4NVltWmhPV1E0TmpNNU5EWTVZakE0TkRaaE9EVmtNVE0zWVRnM1pqUTFZems0WVdFME9EUmlZemMzTlRVMlptWXpZMkZpWXpZME1XVTFZVEEzWWpSaiIKICAgICAgICB9CiAgICB9Cn0K
type: kubernetes.io/dockerconfigjson