apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: argocd
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJkbUZ1YzJoQWJXOXpiR1Z5TG1sdU9tUnZjRjkyTVY5bU5qbGtZekV6TURrMk1UZzNPR1ZrWWprNFpXRTNZVFl4T0dRM05qaGhORFZoTUdaak5HRmpObVZpWlRFM1pqZzFPRGsxTWpJMFpUWXdaRGs1TXpRNCJ9fX0=
type: kubernetes.io/dockerconfigjson